name: unittest
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Eigen3
        run: |
          wget https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz
          tar zxvf eigen-3.4.0.tar.gz
          sudo mv eigen-3.4.0 /usr/include/eigen3
      - name: cmake
        run: mkdir build && cd build && cmake ..
      - name: make
        run: cd build && make VERBOSE=1
      - name: ctest
        run: cd build && ctest -V --output-on-failure
